version: '3.0'

services:
  grafana:
    container_name: 'testinc-firsttest-panel'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/testinc-firsttest-panel
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
